### ISSUE TITLE
Jenis Printer

### ISSUE THREAD

**Issue by mdestafadilah** [prawito/bluetooth-printer-react-native#1]
Halo om, rekomendasi Printer POS nyah juga dong om... dari harga "termurah" sampai "tersultan".

**Comment by prawito** [comment]
Untuk tipe yang saya pake kurang lebih ini:
https://www.tokopedia.com/axelpos/printer-bluetooth-kasir-thermal-80mm-iware-c-81bt-support-moka-pos
Kisaran harga di 400rb an.

Di atas itu silahkan di sesuaikan dengan budget.
Kalau concern saya si mencari printer dengan lebar 80mm. Karena ada keperluan tersebut. Kalau kalian mau cari yang jenis lain seharusnya sama saja.
